### ISSUE TITLE
`setup.py` import `setup` from both `distutils.core` and `numpy.distutils.core`

### ISSUE THREAD

**Issue by StevenCHowell** [madscatt/sasmol#12]
The first import of setup in `setup.py`gets overwritten by a second import.  Likely the first one is not needed.  

```
import os,sys
from distutils.core import setup
from distutils      import sysconfig
from numpy.distutils.core import Extension, setup
```

**Comment by StevenCHowell** [comment]
I just tested and removing the first import of setup installs fine. I will make this change and do a pull request.

**Comment by madscatt** [comment]
indeed.
