### ISSUE TITLE
The `write_pdb()` method should coerce the resid to an `int`

### ISSUE THREAD

**Issue by StevenCHowell** [madscatt/sasmol#7]
The `read_pdb()` method expects the resid values to be integers.   The `write_pdb()` method does not have this same expectation and consequently will write files that the `read_pdb()` method cannot handle.

**Comment by madscatt** [comment]
I suppose as a programmer if you define resid as a non integer data type then you could write that non-integer data type to file.  In sasio.py (line 443 currently):

` 443             this_resid = int(self._resid[i])`

has been added.  Thus if the resid component can be cast as an int then write_pdb will handle the case.  Unfortunately, if it cannot be cast as an int then write_pdb will crash.
